id: P54076802
initial_creation_type: input
source_metadata:
  title: Jambhala Series
  language: bo
  description: 'Texts related to Jambhala (dzam bha la; rmugs ’dzin), the deity of
    wealth, in all his various forms:'
  volume:
    aa13751c26844ec4854b781579d183ab:
      title: 'The Falling Rain of Blessings: A Brief Daily Practice of the Wealth
        Deity White Jambhala'
      parent: Sādhanas
    3f4b316ccebc41acbe3eefe9e4f87351:
      title: A Sādhana of Jambhala
      parent: Sādhanas
    5898fed8a75047cdbcb6d727276f49f2:
      title: Sang Offering to Yellow Jambhala
      parent: Sang Offering
created_at: '2022-03-01T04:00:04.800929'
last_modified_at: '2022-03-01T04:00:04.800932'
